## Exercício 1:
## Calcule a raiz quadrada de um número inteiro inserido 
## pelo usuário usando o módulo math

# import math
# numeros = int(input('digite o numero para ser elevado aao quadrado \n'))

# raizquadrada = math.sqrt(numeros)
# print(raizquadrada)         

## Exercício 2:
## Calcule o valor absoluto de um número decimal inserido 
## pelo usuário usando o módulo math

# import math
# numeros = int(input('digite o numero para saber o valor absoluto \n'))

# numero_absoluto = math.fabs(numeros)
# print("o resultade é ",numero_absoluto)   

## Exercício 3:
## Arredonde um número decimal inserido pelo usuário para o 
## inteiro mais próximo usando o módulo math

# import math
# numeros = float(input('digite um numero com casa decimal \n'))

# casa_decimal = math.trunc(numeros)
# print(casa_decimal)


## Exercício 4:
## Calcule o seno de um ângulo em graus inserido pelo usuário 
## usando o módulo math.

# import math
# numeros = int(input('digite um numero para descubrir o seu seno \n'))

# seno_sin = math.sin(numeros)
# print(seno_sin)